### ISSUE TITLE
Icons in Gnome Shell are Too Small and Inconsistent

### ISSUE THREAD

**Issue by HymanZHAN** [vinceliuice/Tela-icon-theme#10]
First of all, thank you for putting together such a beautiful icon theme. I like it very much!
However, there are some minor issues.

- Distro: Pop!_OS 19.04

- Display: 4k, 15.6 inch

- Problem:
The icons in the Gnome Shell top bar are too small/of inconsistent size.

- Screenshots:
  - Pop Icon Theme:

![Screenshot from 2019-04-26 10-47-44](https://user-images.githubusercontent.com/26806995/56816215-135b6400-6811-11e9-8b05-556227bb64e0.png)

  - Tela Icon Theme
![Screenshot from 2019-04-26 10-47-12](https://user-images.githubusercontent.com/26806995/56816207-1191a080-6811-11e9-97b4-46431d69dfd4.png)

Notice how small the **Power Off** icon is.

**Comment by HymanZHAN** [comment]
Just to provide more information, I noticed that this scaling issue happened only on non-100% scale, i.e. 200% or 300%. For a 4k 15.6-inch display a 200% scaling is a must so I face this issue all the time. However, I don't experience this issue when using a larger monitor where the scale is 100%.

**Comment by vinceliuice** [comment]
Does this fixed now

**Comment by HymanZHAN** [comment]
I just tried it on PopOS 19.04, and the problem still exists. I will try it on Fedora 30 later and see if there's any difference.

**Comment by vinceliuice** [comment]
I updated the index.theme file, what about now?

**Comment by HymanZHAN** [comment]
Great! I can confirm the problem is solved on Fedora30.

![Screenshot from 2019-07-04 10-29-52](https://user-images.githubusercontent.com/26806995/60673996-1db86080-9e47-11e9-95ab-c005a7d7b728.png)

Closing the issue now and if there's any update on other systems (which seems unlikely) I will let you know.

Thank you for fixing this!
